### ISSUE TITLE
Make it work with the package manager!

### ISSUE THREAD

**Issue by TheTS** [ollydev/WindowOverlay#1]
http://puu.sh/zVaDv/85b2e2d8e1.png

**Comment by ollydev** [comment]
I'm assuming it doesn't work because it's installing under the libWindowOverlay folder, where the include looks for WindowOverlay folder?

**Comment by TheTS** [comment]
That, and it doesn't have the .dll because it's not in the repository

**Comment by ollydev** [comment]
1008 days later I have fixed this issue.
